---
title: "Homework 5"
author: "Isabelle Smith"
date: "2025-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(777)
```

&nbsp;

### Question 1

```{r}

set.seed(7)

# Assign to the variable n_dims a single random integer between 3 and 10.
n_dims <- sample(3:10,1)


# Create a vector of consecutive integers from 1 to n_dims^2.
vec <- 1:(n_dims^2)


# Use the sample function to randomly reshuffle these values.
vec2 <- sample(vec, length(vec), replace=FALSE)


# create a square matrix with these elements.
mat <- matrix(vec2, nrow=n_dims, byrow=TRUE)


# print out the matrix.
print(mat)


# find a function in r to transpose the matrix.
mat_t <- t(mat)


# print it out again and note how it has changed.
print(mat_t)


# calculate the sum and the mean of the elements in the first row and then the last row.
sum(mat_t[,1])
mean(mat_t[,1])
sum(mat_t[,n_dims])
mean(mat_t[,n_dims])


# read about the eigen() function and use it on your matrix
##?eigen()
mat_t_e <- eigen(mat_t)


# look carefully at the elements of $values and $vectors in the output. What kind of numbers are these?
mat_t_e$values
mat_t_e$vectors
                ## they are imaginary/complex numbers


# dig in with the typeof() function to figure out their type.
typeof(mat_t_e$values)
typeof(mat_t_e$vectors)


# if have set your code up properly, you should be able to re-run it and create a matrix of different size because n_dims will change.

```


&nbsp;

### Question 2

```{r}

# Create a list with the following named elements:
# my_matrix, which is a 4 x 4 matrix filled with random uniform values
# my_logical which is a 100-element vector of TRUE or FALSE values. Do this efficiently by setting up a vector of random values and then applying an inequality to it.
# my_letters, which is a 26-element vector of all the lower-case letters in random order.

my_matrix <- matrix(runif(4^2), nrow=4, byrow=TRUE)

my_logical <- rpois(100,7) < 7

my_letters <- sample(letters, 26, replace=FALSE)

list1 <- list(my_matrix, my_logical, my_letters)


# Then, complete the following steps:
# create a new list, which has the element[2,2] from the matrix, the second element of the logical vector, and the second element of the letters vector.
# use the typeof() function to confirm the underlying data types of each component in this list
# combine the underlying elements from the new list into a single atomic vector with the c() function.
# what is the data type of this vector?

list2 <- list(list1[[1]][2,2], list1[[2]][2], list1[[3]][2])

typeof(list2[[1]])
typeof(list2[[2]])
typeof(list2[[3]])

vec1 <- c(list2[[1]], list2[[2]], list2[[3]])

typeof(vec1)
            ## it's a character vector

```


&nbsp;

### Question 3

```{r}

# Create a data frame with the two variables (= columns) and 26 cases (= rows) below:
# call the first variable my_unis and fill it with 26 random uniform values from 0 to 10
# call the second variable my_letters and fill it with 26 capital letters in random order.

# for the first variable, use a single line of code in R to select 4 random rows and replace the numerical values in those rows with NA.
# for the first variable, write a single line of R code to identify which rows have the missing values.

# re-order the entire data frame to arrange the second variable in alphabetical order

# calculate the column mean for the first variable.

df <- data.frame(my_unis = runif(26,min=0,max=10),
                 my_letters = sample(LETTERS, 26, replace=FALSE))
df

df$my_unis[sample(1:26,4,replace=FALSE)] <- NA
df[is.na(df$my_unis),]

df2 <- df[order(df$my_letters),]
df2

mean(df$my_unis, na.rm=TRUE)

```


